### ISSUE TITLE
Time to meet for future meetups

### ISSUE THREAD

**Issue by chrisplatorres** [M3-org/proposals#3]
It has now been mentioned a few times that 6pm PST is not a good time for other time zones, specifically EU people. What time would future meetups have to be at to be able to include the most people?

It was brought up that bi-weekly is a good pace and that we can alternate between 9am PST and 6pm PST meetups to accommodate for EU time zones and for people who are busy during typical working hours (9-5).

**Comment by rzr** [comment]
Please ++ this comment if you're in West EU zone...

Feel free to add other time zone and vote on the one you're belonging to.

Welcome to the Votiverse :)

**Comment by nnnnicholas** [comment]
Eastern Standard Time, GMT -5.

For those in this time zone with daytime work schedules, 6PM PST is preferred.

**Comment by blairmacintyre** [comment]
@nnnnicholas don't count all us EST-ers with the PST-ers. :)    I'm on EST and work during the day, but this essentially _is_ work, so I'll likely do the 9am PST (noon here) meetings more often than the 6pm PST (9pm) meetings (over the years I've become less inclined to have optional work stuff impinge on family/personal time ...)

**Comment by chrisplatorres** [comment]
[Updated schedule here](https://github.com/open-metaverse-gathering/schedule/blob/master/README.md) for the Thursday May 2nd meet. It will be at 6pm PST, but we will go over the comments here where @rzr and @blairmacintyre would be able to make 9am PST instead.

**Comment by chrisplatorres** [comment]
@arpu mentioned that 11:30am PST is a good time for Vienna ( UTC +2 CEST )

**Comment by rzr** [comment]
Please remind us when is next meeting(s) here
may I suggest to use UTC date and add link to other TZ using 
http://time.is/

**Comment by rzr** [comment]
According to:
https://github.com/M3-org/proposals/issues/4

There is a meeting planned in very soon:

* https://time.is/0200_26_May_2019_UTC/PST/EST/EU/CST/CET#
* 02:00 on Sunday, May 26, 2019 UTC 
* Saturday May 25 at 6pm PST

Please remind us the entry door link here ?

**Comment by vyrnix9582046173** [comment]
#4 is a [separate event](https://github.com/M3-org/proposals/issues/4#issuecomment-495043286) that will take place tomorrow at those times. That is a separate event from the bi-weekly meets.

The schedule for meets is in this repo: https://github.com/M3-org/schedule


Going to close this issue as we're continuing meeting at 6pm PST.
